version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/khaddemApp
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
    depends_on:
      - db
    ports:
      - "8089:8089"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: khaddemApp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
